/*!
 * cdp.lazyload.d.ts 
 * This file is generated by the CDP package build process.
 *
 * Copyright 2015 Sony Corporation
 * Released under the MIT license
 *
 * Date: 2015-07-16T20:01:05
 */
﻿declare module CDP {
    /**
    * \~english
    * Script lazy loading.
    *
    * \~japanese
    * 遅延スクリプトロード
    *
    * @param type {String} [in] script タグに指定されたタイプを指定
    */
    function lazyLoad(type: string): void;

    /**
     * \~english
     * Check for AMD is available.
     *
     * \~japanese
     * AMD が使用可能か判定
     *
     * @private
     * @return {Boolean} true: AMD 対応環境 / false: AMD 非対応
     */
    function isAMD(): boolean;
}
